### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by yangzuokun** [RNAcentral/auto-traveler#6]
Fetched 10.2 MB in 7min 11s (23.5 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file

**Comment by AntonPetrov** [comment]
Thank you for reporting this error. Could you please paste the complete log showing the progress of `docker build`?

**Comment by yangzuokun** [comment]
docker build -t auto-traveler .
Sending build context to Docker daemon  248.6MB
Step 1/28 : FROM gcc:4.9
 ---> 1b3de68a7ff8
Step 2/28 : RUN apt-get update
 ---> Running in e28583fcf22c
Ign http://deb.debian.org jessie InRelease
Get:1 http://deb.debian.org jessie-updates InRelease [7340 B]
Get:2 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Get:4 http://deb.debian.org jessie Release [148 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [849 kB]
Get:6 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.2 MB in 13s (774 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update' returned a non-zero code: 100

**Comment by AntonPetrov** [comment]
Thanks! Could you please try the solution suggested here?
https://superuser.com/questions/1423486/issue-with-fetching-http-deb-debian-org-debian-dists-jessie-updates-inrelease?answertab=votes#tab-top

I can't test it out myself right now unfortunately. Thank you!

**Comment by AntonPetrov** [comment]
A pre-built image is now also available on Docker Hub: https://hub.docker.com/r/rnacentral/auto-traveler. Thank you for raising this issue!
